PostBlog.WebApp/PostBlog.Bootstraper/Controllers/PublicViewerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PostBlog.Bootstraper.Models;
using PostBlog.Common.Enums;
using PostBlog.Common.Models;
using PostBlog.Common.Services.Interfaces;

namespace PostBlog.Bootstraper.Controllers
{
    public class PublicViewerController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ILogger<PosterController> _logger;
        private readonly IPostDetailRepository _postDetailRepository;
        public PublicViewerController(
            IPostRepository postRepository,
            IPostDetailRepository postDetailRepository,
            ILogger<PosterController> logger)
        {
            _postRepository = postRepository;
            _postDetailRepository = postDetailRepository;
            _logger = logger;
        }

        // GET: PublicViewer
        public ActionResult Index()
        {
            var listPost = _postRepository.FindByCondition(t=>t.PostState == StateEnum.APPROVED.ToString());
            if (listPost.Any())
            {
                return View(listPost);
            }
            List<Post> list = new List<Post>();
            return View(list);
        }

        // GET: PublicViewer/Details/5
        public ActionResult AddComments(string id)
        {
            var post = _postRepository.FindByCondition(t => t.PostId == id).FirstOrDefault();
            var postDetails = _postDetailRepository.FindByCondition(t => t.PostId == post.PostId).OrderByDescending(t=>t.AuditCreatedOnDate).ToList();
            PostViewModel postViewModel = new PostViewModel
            {
                PostId = post.PostId,
                Title = post.Title,
                Content = post.Content,
                PostDetails = postDetails
            };
            return View(postViewModel);
        }

        // POST: PublicViewer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComments(PostViewModel postView)
        {
            try
            {
                _postDetailRepository.Create(new PostDetail
                {
                    PostDetailtId = Guid.NewGuid().ToString(),
                    PostId = postView.PostId,
                    Comments = postView.PostDetail.Comments,
                    CommentsAutor = postView.PostDetail.CommentsAutor,
                    AuditCreatedOnDate = DateTime.Now
                });

                _postDetailRepository.SaveChanges();
                return Redirect($"AddComments?id={postView.PostId}");
            }
            catch 
            {
                return View();
            }
        }

        // GET: PublicViewer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PublicViewer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PublicViewer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PublicViewer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PostBlog.WebApp/PostBlog.Bootstraper/Views/PublicViewer/AddComments.cshtml
@model PostViewModel
@{
    ViewData["Title"] = "AddComments";
    Layout = "~/Views/Shared/_Layout_Main.cshtml";
}

<form method="post" asp-action="AddComments" asp-controller="PublicViewer">
    <input type="hidden" asp-for="@Model.PostId"  />
    <div class="container-fluid">
        <div class="mb-3">
            <label for="autor_id" class="form-label">Title</label>
            <input type="text" asp-for="Title" class="form-control form-control-sm" id="autor_id" readonly>
        </div>
        <div class="mb-3">
            <label for="content2_id" class="form-label">Post Content</label>
            <textarea asp-for="Content" class="form-control form-control-sm" id="content2_id" rows="3" readonly></textarea>
        </div>

        <div class="mb-3">
            <label for="autor2_id" class="form-label">Your Name</label>
            <input type="text" asp-for="PostDetail.CommentsAutor" class="form-control form-control-sm" id="autor2_id">
        </div>
        <div class="mb-3">
            <label for="content_id" class="form-label">Add Comments</label>
            <textarea asp-for="PostDetail.Comments" class="form-control form-control-sm" id="content_id" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-success btn-sm">Save Comment</button>
    </div>
</form>
<h3 class="text-center mb3">Comments</h3>
@if (Model.PostDetails.Any())
{
    @foreach (var item in Model.PostDetails)
    {
        <div class="card mt-2 mb-3">
            <div class="card-body">
                <h5 class="card-title">@item.CommentsAutor</h5>
                <p class="card-text">@item.Comments</p>
                <p class="card-subtitle">@item.AuditCreatedOnDate</p>
            </div>
        </div>
    }
}

PostBlog.WebApp/PostBlog.Bootstraper/Views/PublicViewer/Index.cshtml
@model IEnumerable<Post>
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout_Main.cshtml";
}

@if (Model.Any())
{
    @foreach (var item in Model)
    {
    <div class="card mt-2 mb-3">
        <div class="card-body">
            <h5 class="card-title">@item.Title</h5>
            <p class="card-text">@item.Content</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item item-secondary">Approved Date: @item.ApprovedDate.ToShortDateString()</li>
            <li class="list-group-item item-secondary">Autor: @item.PostAutor</li>
        </ul>
        <div class="card-footer">
            <a  asp-controller="PublicViewer" asp-action="AddComments" asp-route-id="@item.PostId"> Add comments </a>
        </div>
    </div>
    }
}